# Generated by Django 5.2.7 on 2025-10-22 16:40

import ProveedoresApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProveedoresApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='codigo_proveedor',
            field=models.CharField(default=ProveedoresApp.models.generar_code, max_length=32, unique=True),
        ),
    ]
