# Generated by Django 5.2.7 on 2025-10-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Botique', '0002_delete_orden'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalago',
            new_name='Catalogo',
        ),
    ]
