# Generated by Django 5.2.7 on 2025-11-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('medidas', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('abono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(choices=[('Bs', 'Bs'), ('$', '$')], default='bs', max_length=3)),
                ('accion', models.CharField(choices=[('Diseño', 'Diseño'), ('Toma de Medidas', 'Toma de Medidas'), ('Pruebas', 'Pruebas'), ('Entrega', 'Entrega'), ('Culminado', 'Culminado'), ('Cancelada', 'Cancelada'), ('Otros', 'Otros')], default='otros', max_length=20)),
            ],
            options={
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
