# Generated by Django 5.2.7 on 2025-11-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='accion',
            field=models.CharField(choices=[('toma_medidas', 'Toma de Medidas'), ('pruebas', 'Pruebas'), ('retiro', 'Retiro'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
    ]
