# Generated by Django 5.2.7 on 2025-11-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='medidas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='moneda',
            field=models.CharField(choices=[('bs', 'Bs'), ('usd', '$')], default='bs', max_length=3),
        ),
    ]
