# Generated by Django 5.2.7 on 2025-11-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_cita_abono_alter_cita_pago_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='medidas',
        ),
        migrations.AddField(
            model_name='cita',
            name='busto',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='cintura',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='largo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='otra',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
