# Generated by Django 5.2.7 on 2025-11-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_remove_cita_medidas_cita_busto_cita_cintura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
