# Generated by Django 5.2.7 on 2025-11-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_cita_fecha_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='accion',
            field=models.CharField(choices=[('Medidas/Diseño', 'Medidas/Diseño'), ('Pruebas', 'Pruebas'), ('Entrega', 'Entrega'), ('Culminado', 'Culminado'), ('Cancelada', 'Cancelada'), ('Otros', 'Otros')], default='otros', max_length=20),
        ),
    ]
