# Generated by Django 5.2.7 on 2025-11-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_alter_cita_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='otra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
