# Generated by Django 5.2.7 on 2025-11-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_cita_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
