# Generated by Django 5.2.7 on 2025-11-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_cita_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='copa',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='tiras',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
