# Generated by Django 5.2.7 on 2025-11-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0002_alter_perfilusuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='ciudad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='pais',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
