# Generated by Django 5.2.7 on 2025-11-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0003_alter_perfilusuario_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
