# Generated by Django 5.2.7 on 2025-11-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='descripcion',
            field=models.TextField(max_length=300),
        ),
    ]
