# Generated by Django 5.2.7 on 2025-10-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='imagen',
        ),
    ]
