# Generated by Django 5.2.7 on 2025-11-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='catalogo',
            name='imagen_modelo',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
