# Generated by Django 5.2.7 on 2025-11-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueApp', '0002_alter_catalogo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
